/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as RspRouteImport } from './routes/rsp'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RspIndexRouteImport } from './routes/rsp.index'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as QuizAdminRouteImport } from './routes/quiz_.admin'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as ApiPublicQuizSubmitRouteImport } from './routes/api/public/quiz-submit'
import { Route as ApiPublicQuizResultTokenRouteImport } from './routes/api/public/quiz-result.$token'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RspRoute = RspRouteImport.update({
  id: '/rsp',
  path: '/rsp',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RspIndexRoute = RspIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RspRoute,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizAdminRoute = QuizAdminRouteImport.update({
  id: '/quiz_/admin',
  path: '/quiz/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicQuizSubmitRoute = ApiPublicQuizSubmitRouteImport.update({
  id: '/api/public/quiz-submit',
  path: '/api/public/quiz-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuizResultTokenRoute =
  ApiPublicQuizResultTokenRouteImport.update({
    id: '/api/public/quiz-result/$token',
    path: '/api/public/quiz-result/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/rsp': typeof RspRouteWithChildren
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/quiz/admin': typeof QuizAdminRoute
  '/r/$token': typeof RTokenRoute
  '/rsp/': typeof RspIndexRoute
  '/api/public/quiz-submit': typeof ApiPublicQuizSubmitRoute
  '/api/public/quiz-result/$token': typeof ApiPublicQuizResultTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/quiz/admin': typeof QuizAdminRoute
  '/r/$token': typeof RTokenRoute
  '/rsp': typeof RspIndexRoute
  '/api/public/quiz-submit': typeof ApiPublicQuizSubmitRoute
  '/api/public/quiz-result/$token': typeof ApiPublicQuizResultTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/rsp': typeof RspRouteWithChildren
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/quiz_/admin': typeof QuizAdminRoute
  '/r/$token': typeof RTokenRoute
  '/rsp/': typeof RspIndexRoute
  '/api/public/quiz-submit': typeof ApiPublicQuizSubmitRoute
  '/api/public/quiz-result/$token': typeof ApiPublicQuizResultTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/quiz'
    | '/rsp'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/app'
    | '/onboarding'
    | '/invite/$token'
    | '/quiz/admin'
    | '/r/$token'
    | '/rsp/'
    | '/api/public/quiz-submit'
    | '/api/public/quiz-result/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/quiz'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/app'
    | '/onboarding'
    | '/invite/$token'
    | '/quiz/admin'
    | '/r/$token'
    | '/rsp'
    | '/api/public/quiz-submit'
    | '/api/public/quiz-result/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/login'
    | '/quiz'
    | '/rsp'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/invite/$token'
    | '/quiz_/admin'
    | '/r/$token'
    | '/rsp/'
    | '/api/public/quiz-submit'
    | '/api/public/quiz-result/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  QuizRoute: typeof QuizRoute
  RspRoute: typeof RspRouteWithChildren
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  InviteTokenRoute: typeof InviteTokenRoute
  QuizAdminRoute: typeof QuizAdminRoute
  RTokenRoute: typeof RTokenRoute
  ApiPublicQuizSubmitRoute: typeof ApiPublicQuizSubmitRoute
  ApiPublicQuizResultTokenRoute: typeof ApiPublicQuizResultTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsp': {
      id: '/rsp'
      path: '/rsp'
      fullPath: '/rsp'
      preLoaderRoute: typeof RspRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsp/': {
      id: '/rsp/'
      path: '/'
      fullPath: '/rsp/'
      preLoaderRoute: typeof RspIndexRouteImport
      parentRoute: typeof RspRoute
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz_/admin': {
      id: '/quiz_/admin'
      path: '/quiz/admin'
      fullPath: '/quiz/admin'
      preLoaderRoute: typeof QuizAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/quiz-submit': {
      id: '/api/public/quiz-submit'
      path: '/api/public/quiz-submit'
      fullPath: '/api/public/quiz-submit'
      preLoaderRoute: typeof ApiPublicQuizSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quiz-result/$token': {
      id: '/api/public/quiz-result/$token'
      path: '/api/public/quiz-result/$token'
      fullPath: '/api/public/quiz-result/$token'
      preLoaderRoute: typeof ApiPublicQuizResultTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface RspRouteChildren {
  RspIndexRoute: typeof RspIndexRoute
}

const RspRouteChildren: RspRouteChildren = {
  RspIndexRoute: RspIndexRoute,
}

const RspRouteWithChildren = RspRoute._addFileChildren(RspRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  QuizRoute: QuizRoute,
  RspRoute: RspRouteWithChildren,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  InviteTokenRoute: InviteTokenRoute,
  QuizAdminRoute: QuizAdminRoute,
  RTokenRoute: RTokenRoute,
  ApiPublicQuizSubmitRoute: ApiPublicQuizSubmitRoute,
  ApiPublicQuizResultTokenRoute: ApiPublicQuizResultTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
